algoritmo "SUPERCONTADOR"
// Função :
// Autor :
// Data : 17/01/2022
// Seção de Declarações 
var
      N: inteiro
inicio
Repita
EscrevaL ("=============")
EscrevaL ("|    MENU   |")
EscrevaL ("[1] de 1 a 10")
EscrevaL ("[2] de 10 a 1")
EscrevaL ("[3] Sair")

Leia (N)
Escolha (N)
Caso 1
     EscrevaL ("1 2 3 4 5 6 7 8 9 10")
Caso 2
     EscrevaL ("10 9 8 7 6 5 4 3 2 1")
OutroCaso
     EscrevaL ("Saindo...")
FimEscolha

Ate (N = 3)

fimalgoritmo
