algoritmo "semnome"
// Função :
// Autor :
// Data : 10/01/2022
// Seção de Declarações 
var
   cont, N, soma: inteiro
inicio

      cont <- 1
      soma <- 0
      Enquanto cont <= 10 faca
               Escreva ("Digite o ", cont, ".o valor: ")
               Leia (N)
               soma <- soma + N
               cont <- cont + 1
      FimEnquanto
      Escreva ("A soma de todos os valores foi de: ", soma)


fimalgoritmo
