algoritmo "semnome"
// Função :
// Autor :
// Data : 20/01/2022
// Seção de Declarações 
var
      N1, N2: Real
inicio

Escreva ("Digite um número: ")
Leia (N1)
Escreva ("Digite outro número: ")
Leia (N2)

Se (N1 > N2) entao
   EscrevaL ("O primeiro valor é o maior")
FimSe

Se (N1 < N2) entao
   Escreva ("O segundo valor é o maior")
FimSe

Se (N1 = N2) entao
         Escreva ("Os dois valores são iguais")
FimSe

fimalgoritmo
