algoritmo "semnome"
// Função :
// Autor :
// Data : 29/12/2021
// Seção de Declarações 
var
largura: real
altura: real
area: real
inicio
Escreval ("Largura da parede em metros: ")
Leia (largura)
Escreval ("Altura da parede em metros: ")
Leia (altura)
area <- (altura*largura)
Escreval("A área da parede é de ", area, "m². Você precisará de ", (area/2), "L de Tinta para pintar toda a parede")

fimalgoritmo
